image: "node:latest"

before_script:
  - yarn install

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build html:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - ./build

deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H '18.191.5.73' >> ~/.ssh/known_hosts
  script:
    - yarn build
    - scp -r ./public/ ubuntu@18.191.5.73:/var/www/WeBuild.World/build
  only:
    - develop
